"""
JARVIS AI OS — Prash Tool Call Schema Validator.
=================================================
Validates candidate tool calls emitted by the Prash neural engine before they can
reach the SafetyGatekeeper or ToolRegistry. Enforces strict schema, parameter type,
and tool existence constraints to prevent hallucinated actions or malformed parameters.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Set, Tuple
from loguru import logger

from backend.services.tool_registry import ToolRegistry


@dataclass
class PrashValidationResult:
    is_valid: bool
    tool_name: Optional[str] = None
    parameters: Dict[str, Any] = None
    rejection_reason: Optional[str] = None
    is_conversational: bool = False
    conversational_text: Optional[str] = None


class PrashToolValidator:
    """Validates raw output from Prash to extract verified tool calls or conversational responses."""

    # Schema specs for fast validation of common desktop tools
    KNOWN_TOOL_SPECS: Dict[str, Dict[str, Any]] = {
        "lock_pc": {
            "required": [],
            "allowed": [],
        },
        "take_screenshot": {
            "required": [],
            "allowed": ["monitor_index", "save_path"],
        },
        "get_system_status": {
            "required": [],
            "allowed": ["include_processes", "include_network"],
        },
        "open_application": {
            "required": ["app_name"],
            "allowed": ["app_name", "args", "target_monitor"],
            "types": {"app_name": str},
        },
        "close_application": {
            "required": ["app_name"],
            "allowed": ["app_name", "force"],
            "types": {"app_name": str},
        },
        "media_control": {
            "required": ["action"],
            "allowed": ["action", "volume_delta"],
            "allowed_values": {
                "action": ["play_pause", "next_track", "prev_track", "volume_up", "volume_down", "mute"]
            },
        },
        "toggle_live_mode": {
            "required": [],
            "allowed": ["enable"],
            "types": {"enable": bool},
        },
        "get_proximity_telemetry": {
            "required": [],
            "allowed": [],
        },
        "gmail_list_messages": {
            "required": [],
            "allowed": ["query", "max_results"],
        },
        "gmail_send_message": {
            "required": ["to", "subject", "body"],
            "allowed": ["to", "subject", "body"],
        },
        "google_calendar_list_events": {
            "required": [],
            "allowed": ["time_min", "max_results"],
        },
        "outlook_list_messages": {
            "required": [],
            "allowed": ["unread_only", "max_results"],
        },
        "click_element_by_name": {
            "required": ["element_name"],
            "allowed": ["element_name", "window_title", "match_type"],
        },
        "set_control_value": {
            "required": ["element_name", "value"],
            "allowed": ["element_name", "value", "window_title"],
        },
    }

    def __init__(self, tool_registry: Optional[ToolRegistry] = None) -> None:
        self.tool_registry = tool_registry or ToolRegistry()
        self._registered_tools: Set[str] = set(self.tool_registry.list_tools().keys())

    def validate_raw_response(self, raw_text: str, user_query: str) -> PrashValidationResult:
        """
        Parses Prash output, detects JSON tool blocks, and validates against registry schemas.
        Returns a PrashValidationResult indicating validity, tool name, and parameters.
        """
        if not raw_text or not raw_text.strip():
            return PrashValidationResult(
                is_valid=False,
                rejection_reason="Empty response generated by model"
            )

        # 1. Attempt JSON block extraction
        parsed_json = self._extract_json(raw_text)

        if not parsed_json:
            # If no JSON was found, check if it is a pure conversational / knowledge response
            cleaned_text = raw_text.strip()
            # If the user asked an action query, but model gave pure prose without JSON, reject tool execution
            return PrashValidationResult(
                is_valid=True,
                is_conversational=True,
                conversational_text=cleaned_text
            )

        # 2. Extract tool name & params
        tool_name = parsed_json.get("tool")
        if not tool_name or not isinstance(tool_name, str):
            return PrashValidationResult(
                is_valid=False,
                rejection_reason="JSON block missing 'tool' string key"
            )

        params = parsed_json.get("params", {})
        if not isinstance(params, dict):
            return PrashValidationResult(
                is_valid=False,
                rejection_reason="Tool 'params' is not a dictionary"
            )

        # 3. Check tool existence in ToolRegistry
        if tool_name not in self._registered_tools and tool_name not in self.KNOWN_TOOL_SPECS:
            logger.warning("Prash proposed unregistered tool '{}'", tool_name)
            return PrashValidationResult(
                is_valid=False,
                tool_name=tool_name,
                rejection_reason=f"Tool '{tool_name}' is not registered in ToolRegistry"
            )

        # 4. Validate parameters against KNOWN_TOOL_SPECS if available
        spec = self.KNOWN_TOOL_SPECS.get(tool_name)
        if spec:
            # Check required fields
            for req in spec.get("required", []):
                if req not in params:
                    return PrashValidationResult(
                        is_valid=False,
                        tool_name=tool_name,
                        rejection_reason=f"Missing required parameter '{req}' for tool '{tool_name}'"
                    )

            # Check allowed values
            for param_key, allowed_vals in spec.get("allowed_values", {}).items():
                val = params.get(param_key)
                if val is not None and val not in allowed_vals:
                    return PrashValidationResult(
                        is_valid=False,
                        tool_name=tool_name,
                        rejection_reason=f"Invalid value '{val}' for parameter '{param_key}'. Allowed: {allowed_vals}"
                    )

            # Check parameter types
            for param_key, expected_type in spec.get("types", {}).items():
                val = params.get(param_key)
                if val is not None and not isinstance(val, expected_type):
                    return PrashValidationResult(
                        is_valid=False,
                        tool_name=tool_name,
                        rejection_reason=f"Parameter '{param_key}' must be of type {expected_type.__name__}"
                    )

        # 5. Passed all validation checks
        return PrashValidationResult(
            is_valid=True,
            tool_name=tool_name,
            parameters=params,
            conversational_text=raw_text
        )

    def _extract_json(self, text: str) -> Optional[Dict[str, Any]]:
        """Safely extract JSON object from markdown codeblock or raw brackets."""
        # 1. Regex for ```json { ... } ```
        codeblock_match = re.search(r"```(?:json)?\s*(\{.*?\})\s*```", text, re.DOTALL)
        if codeblock_match:
            try:
                data = json.loads(codeblock_match.group(1))
                if isinstance(data, dict):
                    return data
            except Exception:
                pass

        # 2. Raw JSON string
        try:
            data = json.loads(text.strip())
            if isinstance(data, dict):
                return data
        except Exception:
            pass

        # 3. First balanced { ... } dict containing "tool"
        match = re.search(r"\{[^{}]*\"tool\"\s*:\s*\"[^\"]+\"[^{}]*\}", text)
        if match:
            try:
                data = json.loads(match.group(0))
                if isinstance(data, dict):
                    return data
            except Exception:
                pass

        return None


# Global singleton instance
prash_tool_validator = PrashToolValidator()
